### ISSUE TITLE
1118 TODO

### ISSUE THREAD

**Issue by jjimini98** [jjimini98/generate_novel#3]
### 11/18 TODO 

- [x] mongoDB Database 생성 및 collection 추가 
- [x] pymongo로 데이터 적재 
- [x] novel_preprocessing 코드 확인 -> 추후 필요할 것 같으면 코드 수정 
- [x] gpt_model 코드 손댈 수 있는지 확인 필요
